# Generated by Django 3.0 on 2020-01-17 06:25

from django.db import migrations
from os import environ


def generate_superuser(apps, schema_editor):
        from django.contrib.auth.models import User

        DJANGO_SU_NAME = environ.get('VIZSLA_SU_NAME', 'fovizsla')
        DJANGO_SU_EMAIL = environ.get('VIZSLA_SU_EMAIL', 'fovizsla@vizsla.com')
        DJANGO_SU_PASSWORD = environ.get('VIZSLA_SU_PASSWORD', 'vizsla')

        superuser = User.objects.create_superuser(
            username=DJANGO_SU_NAME,
            email=DJANGO_SU_EMAIL,
            password=DJANGO_SU_PASSWORD)

        superuser.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(generate_superuser)
    ]
