# Generated by Django 3.0.7 on 2020-06-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coincatalog', '0002_issuer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'coincatalog"."currency',
            },
        ),
        migrations.CreateModel(
            name='Mint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'coincatalog"."mint',
            },
        ),
        migrations.CreateModel(
            name='RulingAuthority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'coincatalog"."ruling_authority',
            },
        ),
        migrations.AddField(
            model_name='issuer',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='issuer',
            name='code',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
