# Generated by Django 3.0 on 2019-12-07 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL('CREATE SCHEMA numista', 'DROP SCHEMA numista')
    ]
