# Generated by Django 3.0 on 2019-12-08 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numista', '0002_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='numista_country_id',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='numista_country_name',
            new_name='name',
        ),
    ]
