# Generated by Django 3.0 on 2020-01-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numista', '0003_auto_20191208_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numistaId', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'numista"."currency',
            },
        ),
    ]
