# Generated by Django 3.0 on 2020-01-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numista', '0004_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numistaId', models.IntegerField(unique=True)),
                ('isDated', models.BooleanField()),
                ('year', models.IntegerField()),
                ('calendar', models.CharField(max_length=200)),
                ('gregorianYear', models.IntegerField()),
                ('minYear', models.IntegerField()),
                ('maxYear', models.IntegerField()),
                ('mintLetter', models.CharField(max_length=20)),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'numista"."issue',
            },
        ),
    ]
