# Generated by Django 3.0 on 2020-01-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numista', '0005_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='gregorianYear',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='maxYear',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='minYear',
            field=models.IntegerField(null=True),
        ),
    ]
