# Generated by Django 3.0 on 2020-01-12 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('numista', '0008_auto_20200111_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='coin',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='numista.Coin'),
            preserve_default=False,
        ),
    ]
