# Generated by Django 3.0.3 on 2020-02-13 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numista', '0009_issue_coin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='composition',
            new_name='composition_text',
        ),
        migrations.RenameField(
            model_name='coin',
            old_name='valueCurrency',
            new_name='value_currency',
        ),
        migrations.RenameField(
            model_name='coin',
            old_name='valueText',
            new_name='value_text',
        ),
    ]
