# Generated by Django 3.0.7 on 2020-06-09 19:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('numista', '0011_coininfo'), ('numista', '0012_auto_20200509_2212'), ('numista', '0013_auto_20200527_0832'), ('numista', '0014_auto_20200606_2346')]

    dependencies = [
        ('numista', '0010_auto_20200213_0752'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numistaId', models.IntegerField(unique=True)),
                ('lastDownload', models.DateField(auto_now=True)),
                ('numistaCoin', django.contrib.postgres.fields.jsonb.JSONField()),
                ('numistaIssues', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
            options={
                'db_table': 'numista"."coin_info',
            },
        ),
    ]
