# Generated by Django 3.0.3 on 2020-05-27 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numista', '0012_auto_20200509_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coininfo',
            old_name='numistaIssuers',
            new_name='numistaIssues',
        ),
    ]
