# Generated by Django 3.0.7 on 2020-06-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numista', '0013_auto_20200527_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coininfo',
            name='lastDownload',
            field=models.DateField(auto_now=True),
        ),
    ]
